name: build
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: sbt test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run sbt test
        run: |
          sbt compile
          sbt test
