name: build
on:
  pull_request:
    branches: [master, main]
jobs:
  test:
    name: sbt test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          sbt compile
          sbt test
