name: build
on:
  pull_request:
    branches: [master, main]
jobs:
  test:
    name: sbt test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - run: |
          sbt compile
          sbt test
          sbt scalafmtCheckAll
